fix: improve error message for not yet archived historical weather
ttytm/wthrr-the-weathercrab pull request #188
Opened 2023-07-23 16:58 UTC by tobealive

An improved error message for historical weather data that is not yet available in open-meteo's archives. 

Resolves #135

2023-07-24 17:35 UTC, kevinmatthes requested changes
Thank you for your work on this, @tobealive!  I had a look on your changes and found two minor issues which might need to be adjusted.

2023-07-24 17:35 UTC, kevinmatthes commented on src/modules/weather.rs
> +		// Therefor we check for null values in the temperature.
```suggestion
		// Therefore, we check for null values in the temperature.
```

2023-07-24 17:35 UTC, kevinmatthes commented on src/modules/weather.rs
> +			return Err(anyhow!("The temperature for the requested weather has not yet been archived."));
```suggestion
			return Err(anyhow!("The temperature for the requested day has not yet been archived."));
```

2023-07-26 13:03 UTC, ttytm commented
Thank you @kevinmatthes  
I'm gonna add a test case before merging to follow a good practice here.

2023-07-28 10:04 UTC, kevinmatthes approved these changes

2023-10-20 13:05 UTC, ttytm commented
Now it just became an different API request if the requested date is younger than 5 days, instead additionally needing to check for null values. I would therefore merge this without adding a test for this function.

2023-10-20 13:22 UTC, merged